//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project.
//
// Copyright (c) 2022 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

extension TCFaceidError {
    public struct UnauthorizedOperation: TCErrorType {
        enum Code: String {
            case activateError = "UnauthorizedOperation.ActivateError"
            case activating = "UnauthorizedOperation.Activating"
            case arrears = "UnauthorizedOperation.Arrears"
            case chargeStatusException = "UnauthorizedOperation.ChargeStatusException"
            case nonAuthorize = "UnauthorizedOperation.NonAuthorize"
            case nonactivated = "UnauthorizedOperation.Nonactivated"
            case other = "UnauthorizedOperation"
        }
        
        private let error: Code
        
        public let context: TCErrorContext?
        
        public var errorCode: String {
            self.error.rawValue
        }
        
        /// Initializer used by ``TCClient`` to match an error of this type.
        ///
        /// You should not use this initializer directly as there are no public initializers for ``TCErrorContext``.
        public init ?(errorCode: String, context: TCErrorContext) {
            guard let error = Code(rawValue: errorCode) else {
                return nil
            }
            self.error = error
            self.context = context
        }
        
        internal init (_ error: Code, context: TCErrorContext? = nil) {
            self.error = error
            self.context = context
        }
        
        /// 服务开通异常。
        public static var activateError: UnauthorizedOperation {
            UnauthorizedOperation(.activateError)
        }
        
        /// 服务开通中。
        public static var activating: UnauthorizedOperation {
            UnauthorizedOperation(.activating)
        }
        
        /// 帐号已欠费。
        public static var arrears: UnauthorizedOperation {
            UnauthorizedOperation(.arrears)
        }
        
        /// 计费状态异常。
        public static var chargeStatusException: UnauthorizedOperation {
            UnauthorizedOperation(.chargeStatusException)
        }
        
        /// 账号未实名。
        public static var nonAuthorize: UnauthorizedOperation {
            UnauthorizedOperation(.nonAuthorize)
        }
        
        /// 未开通服务。
        public static var nonactivated: UnauthorizedOperation {
            UnauthorizedOperation(.nonactivated)
        }
        
        /// 未授权操作。
        public static var other: UnauthorizedOperation {
            UnauthorizedOperation(.other)
        }
    }
}

extension TCFaceidError.UnauthorizedOperation: Equatable {
    public static func == (lhs: TCFaceidError.UnauthorizedOperation, rhs: TCFaceidError.UnauthorizedOperation) -> Bool {
        lhs.error == rhs.error
    }
}

extension TCFaceidError.UnauthorizedOperation: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(message ?? "")"
    }
}

extension TCFaceidError.UnauthorizedOperation {
    /// - Returns: ``TCFaceidError`` that holds the same error and context.
    public func toFaceidError() -> TCFaceidError {
        guard let code = TCFaceidError.Code(rawValue: self.error.rawValue) else {
            fatalError("Unexpected internal conversion error!\nPlease file a bug at https://github.com/teco-project/teco to help address the problem.")
        }
        return TCFaceidError(code, context: self.context)
    }
}

extension TCFaceidError.UnauthorizedOperation {
    /// - Returns: ``TCCommonError`` that holds the same error and context.
    public func toCommonError() -> TCCommonError? {
        if let context = self.context, let error = TCCommonError(errorCode: self.error.rawValue, context: context) {
            return error
        }
        return nil
    }
}
